# syntax=docker/dockerfile:1
# check=error=true

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /apps
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /src

COPY ./projects /src/projects
RUN dotnet workload install wasm-tools

# Nota: esto no compila, solo sirve como base para cache de dependencias

FROM base AS final
